Lab 6
evgenyim/telegram-bot pull request #4
Opened 2020-04-09 16:04 UTC by evgenyim

2020-04-20 07:36 UTC, eld0727 requested changes

2020-04-20 07:36 UTC, eld0727 commented on src/main/scala/lab_1/BotStarter.scala
> +      dbs.getAllQuerries().flatMap(ans => reply(ans)).void
По условию нужно только для текущего пользователя

2020-04-22 10:41 UTC, evgenyim commented on src/main/scala/lab_1/BotStarter.scala
> +      dbs.getAllQuerries().flatMap(ans => reply(ans)).void
Поправил

2020-05-07 14:39 UTC, eld0727 approved these changes

2020-05-07 15:15 UTC, merged